name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Install ARM cross tools
      run: |
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2
        mkdir /home/runner/arm-cross-tools
        tar xfj gcc-arm-none-eabi-8-2018-q4-major-linux.tar.bz2 -C /home/runner/arm-cross-tools
        echo "/home/runner/arm-cross-tools/gcc-arm-none-eabi-8-2018-q4-major/bin" >> $GITHUB_PATH
        ls -l /home/runner/arm-cross-tools/gcc-arm-none-eabi-8-2018-q4-major/bin
      
    - name: Install dfu-util
      run: sudo apt install -y dfu-util

    - name: Update submodule
      run: git submodule update --init --recursive
      
    - name: Run make
      run: make

    - name: Archive built firmware
      uses: actions/upload-artifact@v3
      with:
        path: build/ch.elf

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: release_name
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ch.elf
        asset_name: ch.elf
        asset_content_type: application/elf
